server {
 listen 80;
 root /usr/share/nginx/html;
 client_max_body_size 35m;
 add_header X-Content-Type-Options nosniff always;
 location /api/ {
  proxy_pass http://api:8011;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_read_timeout 650s;
  proxy_buffering off;
 }
 location / { try_files $uri $uri/ /index.html; }
}
